[build]
  base    = "app"
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from   = "/"
  to     = "/index.html"
  status = 200

[[redirects]]
  from   = "/peppol-wiki.html"
  to     = "/peppol-wiki.html"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
